"""Write reports/engagenet_review/SUMMARY.md from the JSON artefacts in that directory.

    python training/engagenet/review/summarise.py

Every number in the summary is read from a JSON written by the other review scripts, so the table
cannot drift from its sources. Run the scripts in this order first:

    python training/engagenet/fit_export_lean.py --work C:/engagenet
    python training/engagenet/review/baselines.py --work C:/engagenet
    python training/engagenet/review/face_presence.py --work C:/engagenet
    python training/engagenet/review/calibration.py --work C:/engagenet
    python training/engagenet/review/per_participant.py --work C:/engagenet
    python training/engagenet/review/provenance.py --work C:/engagenet
"""
from __future__ import annotations

import json

import _common as C


def j(name):
    return json.loads((C.OUT / name).read_text(encoding="utf-8"))


def ci(x, d=3):
    return f"[{x[0]:.{d}f}, {x[1]:.{d}f}]" if x else "n/a"


def main() -> int:
    b, f, c, pp, r, pv = (j("baselines.json"), j("face_presence.json"), j("calibration.json"),
                          j("per_participant.json"), j("refit_export.json"), j("provenance.json"))
    L = ["# EngageNet geometry channel: review experiments", "",
         "Generated by `training/engagenet/review/summarise.py` from the JSON files in this "
         "directory. Aggregates only; no per-clip EngageNet data is stored here.", "",
         "Protocol for every row unless stated: fit on the Train subset (2,177 clips / 91 "
         "participants), score once on Test (2,256 clips / 26 participants), the deployed 20 "
         "features, participant-bootstrap 95% intervals (2,000 draws, seed 42), accuracy and "
         "kappa at a 0.5 threshold.", "",
         "## 1. Baselines (binary low engagement)", "",
         "| Model | AUC [95% CI] | Accuracy (majority) | kappa | AP / base rate | JSON |",
         "|---|---|---|---|---|---|"]
    names = {"prior": "Prior (constant)", "mean_gaze_y_raw": "Mean gaze-y, raw score",
             "mean_gaze_y_logistic": "Mean gaze-y, logistic", "logistic_regression":
             "Logistic regression (L2, 20 features)", "random_forest": "Random forest (500 trees)",
             "gbdt_refit": "GBDT refit (sklearn " + b["versions"]["scikit_learn"] + ")",
             "gbdt_committed": "GBDT deployed (committed predictions)"}
    for k, lab in names.items():
        x = b["binary"][k]
        L.append(f"| {lab} | {x['auc']:.3f} {ci(x['auc_ci95_participant'])} | "
                 f"{x['accuracy']:.3f} ({x['majority_baseline']:.3f}) | {x['kappa']:.3f} | "
                 f"{x['ap_over_base_rate']:.2f} | `baselines.json` binary.{k} |")
    L += ["", "Paired participant-bootstrap AUC differences (deployed GBDT minus baseline):", "",
          "| Comparison | Delta AUC [95% CI] | JSON |", "|---|---|---|"]
    for k, x in b["paired_vs_gbdt_committed"].items():
        L.append(f"| {k.replace('gbdt_committed_minus_', 'GBDT - ')} | {x['delta_auc']:+.4f} "
                 f"{ci(x['ci95_participant'], 4)} | `baselines.json` paired_vs_gbdt_committed.{k} |")
    fc = b["four_class"]
    L += ["", "## 2. Four-class result", "",
          "| Variant | Accuracy [95% CI] | Macro-F1 | Majority | JSON |", "|---|---|---|---|---|"]
    for k in ("balanced", "unweighted"):
        L.append(f"| GBDT, {k} class weights | {fc[k]['accuracy']:.3f} "
                 f"{ci(fc[k]['accuracy_ci95_participant'])} | {fc[k]['macro_f1']:.3f} | "
                 f"{fc['test_majority_accuracy']:.3f} | `baselines.json` four_class.{k} |")
    L += ["", f"EngageNet paper, best 4-class test accuracy: {fc['engagenet_paper_best_test_accuracy']:.4f}. "
          + fc["comparability"], "",
          "## 3. Face presence under the deployed rule", "",
          f"Rule: {f['counts']['rule']} (the browser's 50% floor over the 10 scored frames).", "",
          "| Set | Clips | Positive rate | AUC [95% CI] | JSON |", "|---|---|---|---|---|"]
    cnt = f["counts"]
    L.append(f"| All Test clips | {cnt['all_clips']['n']} | {cnt['all_clips']['positive_rate']:.3f} | "
             f"{f['auc']['all_clips']['auc']:.3f} {ci(f['auc']['all_clips']['auc_ci95_participant'])} | "
             "`face_presence.json` auc.all_clips |")
    L.append(f"| Scorable (>= 5 face frames) | {cnt['scorable']['n']} | "
             f"{cnt['scorable']['positive_rate']:.3f} | "
             f"{f['auc']['scorable_only_deployment_rule']['auc']:.3f} "
             f"{ci(f['auc']['scorable_only_deployment_rule']['auc_ci95_participant'])} | "
             "`face_presence.json` auc.scorable_only_deployment_rule |")
    L.append(f"| All 10 frames with a face | {cnt['all_frames_with_face']['n']} | "
             f"{cnt['all_frames_with_face']['positive_rate']:.3f} | "
             f"{f['auc']['all_frames_with_face_only']['auc']:.3f} "
             f"{ci(f['auc']['all_frames_with_face_only']['auc_ci95_participant'])} | "
             "`face_presence.json` auc.all_frames_with_face_only |")
    L.append(f"| Unscorable (< 5 face frames) | {cnt['unscorable']['n']} | "
             f"{cnt['unscorable']['positive_rate']:.3f} | not scored in deployment | "
             "`face_presence.json` counts.unscorable |")
    L.append(f"| No face in any frame | {cnt['no_face_in_any_frame']['n']} | "
             f"{cnt['no_face_in_any_frame']['positive_rate']:.3f} | | "
             "`face_presence.json` counts.no_face_in_any_frame |")
    L += ["", f"Unscorable clips hold {cnt['share_of_test_positives_in_unscorable']:.1%} of Test "
          f"positives; clips with any missing frame hold "
          f"{cnt['share_of_test_positives_with_any_missing_frame']:.1%}.", "",
          "## 4. Gate sweep (2 consecutive, cooldown 3, recording order per participant)", "",
          "Offers per hour read each window as a 30 s serving cycle (the 10 s clip reading is in "
          "the JSON and is three times higher). Scorable rows mask unscorable windows the way the "
          "deployed gate sees them.", "",
          "| Floor | All: offers | All: precision [CI] | All: lift | Scorable: offers | "
          "Scorable: precision [CI] | Scorable: lift | Platt: offers | Platt: precision [CI] |",
          "|---|---|---|---|---|---|---|---|---|"]
    A = f["gate_sweep"]["all_clips"]["rows"]
    S = f["gate_sweep"]["scorable_masked_deployment_rule"]["rows"]
    P = c["gate_sweep_recalibrated"]["rows"]
    for ra, rs, rp in zip(A, S, P):
        fl = "none" if ra["floor"] is None else f"{ra['floor']:.2f}"
        L.append(f"| {fl} | {ra['interventions']} | {ra['precision']:.3f} "
                 f"{ci(ra['ci95_participant'])} | {ra['lift']:.2f} | {rs['interventions']} | "
                 f"{rs['precision']:.3f} {ci(rs['ci95_participant'])} | {rs['lift']:.2f} | "
                 f"{rp['interventions']} | {rp['precision']:.3f} {ci(rp['ci95_participant'])} |")
    a70 = next(x for x in A if x["floor"] == 0.70)
    s70 = next(x for x in S if x["floor"] == 0.70)
    L += ["", f"At 0.70: all clips {a70['interventions']} offers, one every "
          f"{a70['as_30s_cycle']['minutes_between']:.1f} min (30 s reading) or "
          f"{a70['as_10s_clip']['minutes_between']:.1f} min (10 s reading); scorable "
          f"{s70['interventions']} offers, one every {s70['as_30s_cycle']['minutes_between']:.1f} min. "
          "JSON: `face_presence.json` gate_sweep, `calibration.json` gate_sweep_recalibrated.", "",
          "## 5. Calibration of the deployed Test scores", "",
          "| Scores | ECE (10 bins) | Brier | Mean score | Base rate | JSON |", "|---|---|---|---|---|---|"]
    for k, lab in (("test_before", "Deployed"), ("test_after_platt", "Platt, fitted on Train OOF")):
        x = c[k]
        L.append(f"| {lab} | {x['ece']:.4f} | {x['brier']:.4f} | {x['mean_score']:.3f} | "
                 f"{x['base_rate']:.3f} | `calibration.json` {k} |")
    L += ["", "## 6. Per-participant Test AUC", "",
          f"{pp['with_both_classes']} of {pp['participants']} participants have both classes "
          f"({pp['single_class']} single-class). Median {pp['median']:.3f}, IQR "
          f"{ci(pp['iqr'])}, minimum {pp['min']:.3f}, {pp['below_0_5']} below 0.5, "
          f"{pp['below_0_7']} below 0.7. JSON: `per_participant.json`.", "",
          "## 7. Reproducibility of the deployed model", "",
          "| Quantity | Value | JSON |", "|---|---|---|"]
    ta, pc = r["test_auc"], r["per_clip"]
    L += [f"| Test AUC, committed dump / committed ONNX | {ta['committed_dump']:.4f} / "
          f"{ta['committed_onnx']:.4f} | `refit_export.json` test_auc |",
          f"| Test AUC, refit sklearn / refit ONNX | {ta['refit_sklearn']:.4f} / "
          f"{ta['refit_onnx']:.4f} | `refit_export.json` test_auc |",
          f"| Refit ONNX vs refit estimator, max per-clip diff | "
          f"{pc['refit_onnx_vs_refit_sklearn']['max_abs_diff']:.1e} | `refit_export.json` per_clip |",
          f"| Refit vs committed model, max / mean per-clip diff | "
          f"{pc['refit_onnx_vs_committed_onnx']['max_abs_diff']:.4f} / "
          f"{pc['refit_onnx_vs_committed_onnx']['mean_abs_diff']:.4f} | `refit_export.json` per_clip |",
          f"| Refit export size, latency per clip | {r['export_bytes']} bytes, "
          f"{r['latency_ms_per_clip']:.3f} ms (measured under load; not comparable with fit_report.json) | `refit_export.json` |",
          f"| Library versions | sklearn {r['versions']['scikit_learn']}, skl2onnx "
          f"{r['versions']['skl2onnx']}, onnx {r['versions']['onnx']}, onnxruntime "
          f"{r['versions']['onnxruntime']} | `refit_export.json` versions |",
          "", "## 8. Provenance", ""]
    lf, ts = pv["label_files"], pv["train_subset"]
    L += [f"- Label files (modification times predate the local copy, so they come from the source): Train {lf['Train']['mtime'][:10]} "
          f"({lf['Train']['rows']} rows), Validation {lf['Validation']['mtime'][:10]} "
          f"({lf['Validation']['rows']} rows), Test {lf['Test']['mtime'][:10]} "
          f"({lf['Test']['rows']} rows, CSV with columns {lf['Test']['columns']}).",
          f"- Video was copied from the rclone remote `{pv['download']['rclone_remote']}`; no script "
          "records where the label files came from.",
          f"- Train subset: {ts['clips']} clips from {ts['participants']} participants, at most "
          f"{ts['max_clips_per_participant']} per participant ({ts['participants_at_cap_27']} at the cap); "
          f"positive rate {ts['positive_rate_subset']:.3f} against {ts['positive_rate_full_train_excl_snp']:.3f} "
          "for the full split. The generator of the file list is not committed.",
          "", "JSON: `provenance.json`.", ""]
    (C.OUT / "SUMMARY.md").write_text("\n".join(L), encoding="utf-8")
    print(f"  wrote {(C.OUT / 'SUMMARY.md').relative_to(C.REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
